version: "3.8"

services:

  bootcamp_api:
    container_name: bootcamp_project
    image: stepalom/bootcamp_project:0.0.2
    build:
      context: .
    ports:
      - 2000:2000
    environment:
      - PORT=2000
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - MONGODB_CONNSTRING=mongodb://root:example@mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
