version: "3.8"

services:

  bootcamp_api:
    container_name: bootcamp_project
    image: stepalom/bootcamp_project:0.0.1
    build:
      context: .
    ports:
      - 2000:2000
    environment:
      - PORT=2000
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/

    depends_on:
      - mongo_data
  mongo_data:
    container_name: mongo_db
    image: mongo
    restart: always
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
